restoring eps_nuc_neu to split burn zones
MESAHub/mesa pull request #492
Opened 2023-02-13 07:11 UTC by Debraheem

restoring eps_nuc_neu to zones undergoing operator split burn. This fixes the history output for 'eps_nuc_neu_total', 'log_Lneu', and 'log_Lneu_nuc'

2023-02-13 12:51 UTC, rjfarmer requested changes

2023-02-13 12:51 UTC, rjfarmer commented on star/private/struct_burn_mix.f90
> +         s% eps_nuc_neu_total(k) = ending_eps_neu_total ! restore eps_nuc_neu to zones
This needs to have the comment on one line otherwise we can't compile it

2023-02-13 19:44 UTC, Debraheem commented
fixed and made another pr.

2023-02-13 20:03 UTC, rjfarmer commented
I don't think you needed to make a new PR. Just keep pushing commits to this branch and they will stay in this pr

2023-02-14 08:22 UTC, rjfarmer approved these changes

2023-02-14 12:25 UTC, merged